---
- hosts: tag_Group6Ansible
  gather_facts: True
  become: yes
  vars:
      ansible_user	: ec2-user
      ansible_ssh_private_key_file	: /home/ec2-user/environment/acs-project-group6/Prod/Webserver/projectkey
  tasks:

   - name: Install Apache Web Server for RPM
     yum: name=httpd state=latest
     when: ansible_os_family == "RedHat"
    
   - name: Print Linux Family
     debug: var=ansible_os_family
     
   - name: Copy script file to target host
     copy:
      src: ./install_httpd.sh
      dest: /var/www/html/install_httpd.sh
      mode: '0755'

   - name: Execute script file on target host
     command: /var/www/html/install_httpd.sh     
      
   - name: Start Apache Web Server
     service: name=httpd state=started enabled=yes
     when: ansible_os_family == "RedHat"
      
   - shell: /usr/bin/uptime
     register: result
      
   - name: Print result variable
     debug: 
        var: result
    
   - name: Print debug message
     debug: 
        msg: "The result was {{ result }}"
    
  handlers:
  - name: Restart Httpd
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"

    
    
